### ISSUE TITLE
Project name and first release tag

### ISSUE THREAD

**Issue by HarlemSquirrel** [amazing-print/amazing_print#10]
I see that in forking Awesome Print we also got the tags. Should we tag the first release as v2.0.0 to avoid any confusion or maybe [scrub the tags](https://stackoverflow.com/questions/19542301/delete-all-tags-from-a-git-repository) and start over?

While I do like the Awesomer Print name, I'm wondering if it may be a bit _too_ close to it's ancestor and cause confusion. Since we haven't yet made our first release, now is the time to decide this. Naming things is one of the hardest things to do :slightly_frowning_face: 

### Possible alternative project names

We should consider any existing gems by searching https://rubygems.org

#### Preserving `ap` command and `#ai` method
 
- Amazing Print `amazing_print`
- AwePrint `aweprint`
- AwePuts `aweputs`
- Awesome Puts `awesome_puts`

#### Not preserving `ap` command and `#ai` method

- Exploder `exploder` `ep` `"string.ei`
- GadgetInspector `gadgetinspector` `gp` `"string".gi`
- SweetPrint `sweetprint` `sp` `"string".si`

**Comment by attenzione** [comment]
suggestion: `BetterPrint` and `better_print`
also 👍  for  `AmazingPrint`

**Comment by paddor** [comment]
👍 for `AmazingPrint`.
But like I said, I'm okay with `AwesomerPrint` too.

If `#ap` and `#ai` are not preserved, there has to be an optional compatibility layer.

**Comment by HarlemSquirrel** [comment]
OK, what about potential conflicts if someone has both AwesomePrint and this new library installed? Would having the same `#ap` and `#ai` methods defined be more or less confusing?

I think either way, we should indicate that this gem should _not_ be used beside AwesomePrint.

**Comment by paddor** [comment]
Good point. Definitely indicate it. This is a replacement for the time being.

**Comment by ramonsantos** [comment]
:+1:  for `AmazingPrint`.

**Comment by HarlemSquirrel** [comment]
Tags are gone. Org and repo are renamed
