### ISSUE TITLE
v1.5 contains a breaking change due to the string convenience methods being removed

### ISSUE THREAD

**Issue by basicallydan** [amazing-print/amazing_print#100]
Hey folks,

First of all thanks for all the hard work on amazing_print, it's such a handy library for friendlier cli and debuging.

This may be a topic of debate but I believe #91 was a breaking change and should have caused a major version bump under Semantic Versioning guidelines, but it was included in an upgrade from 1.4 to 1.5. The monkey-patching of `String` may have been gross but it's public API and it's part of the `README`, and thus by removing it, dependants' implementations could be broken unexpectedly.

I understand it's our responsibility as users of the third-party libraries to ensure new versions of libraries don't break our software but the reality is that many organisations aren't very thorough or often trust in SemVer to make decisions for them. Sadly this did happen in the case of my org! It's a relatively easy fix, but I wanted to share my perspective and I hope it's welcome.

Finally, the README is out of date as it still includes references to the convenience method. I will happily submit a PR to update it.

Again, keep up the good work and thanks.

**Comment by HarlemSquirrel** [comment]
Thanks for this. I'm not sure how we missed that but I suspect it's because we don't use that feature ourselves :/

I did update the release notes but I don't think this warrants a release yank.
