### ISSUE TITLE
`ruby19_syntax` doesn't work with colorized output

### ISSUE THREAD

**Issue by jacob-carlborg-apoex** [amazing-print/amazing_print#112]
When `ruby19_syntax` option is set to `true` alone, it formats a hash using the 1.8 syntax. But when `plain` is set to `true` as well, it works as expected. Here's an example:

```
pry(main)> ap({foo: 3, bar: 4}, { ruby19_syntax: true })
{
  :foo => 3,
  :bar => 4
}
=> nil
pry(main)> ap({foo: 3, bar: 4}, { ruby19_syntax: true, plain: true })
{
  foo: 3,
  bar: 4
}
=> nil
```

I did a bit of digging and this is what I found. The problem is that `symbol?` always returns `false` here:

https://github.com/amazing-print/amazing_print/blob/4c8dc6406b505e91e707f13bd3a6b00b75ac7e89/lib/amazing_print/formatters/hash_formatter.rb#L51

That's because the keys of the hash have already been colorized by the call to `printable_keys` here:

https://github.com/amazing-print/amazing_print/blob/4c8dc6406b505e91e707f13bd3a6b00b75ac7e89/lib/amazing_print/formatters/hash_formatter.rb#L46

For my first example, `data` in the above snippet contains the following:

```ruby
[["\e[0;36m:foo\e[0m", 3], ["\e[0;36m:bar\e[0m", 4]
```

In the second example, `data` contains the following:

```ruby
[[":foo", 3], [":bar", 4]]
```

The implementation of `symbol?` checks if the first letter is `:`, which is false when the keys have been colorized:

https://github.com/amazing-print/amazing_print/blob/4c8dc6406b505e91e707f13bd3a6b00b75ac7e89/lib/amazing_print/formatters/hash_formatter.rb#L84-L86

**Comment by HarlemSquirrel** [comment]
Thank you for all your work here! I have a fix baking. If you have a chance to try it out I would appreciate it.
