### ISSUE TITLE
Scrub change log

### ISSUE THREAD

**Issue by HarlemSquirrel** [amazing-print/amazing_print#14]
I think that now we've renamed the project and removed the previous tags, we should begin with a clean change log.

**Comment by dewey** [comment]
Isn't it usually the case that you leave credits, licenses and changelogs from the original project in place and just "append" your new changes? I think that'd make it a bit clearer to everyone what's going on.

Also the line in the README is wrong:

```
Amazing Print is a fork of AmazingPrint 
```

**Comment by HarlemSquirrel** [comment]
Good catch on the README. I just fixed that. 

I didn't want to leave the change log since we decided to start the version over and scrubbed the previous tags. That means there would be no reasonable way to check out those previous versions in this project. 

I'm no license expert, just wanted to make sure there was no confusion. I added back the original copyright line to the gem spec. Any other specific recommendations?

**Comment by dewey** [comment]
Fair enough, I'd just make sure proper credit to the original project is given and there's a link back to the original project so people can look up older issues / the old changelog file or other discussions. Not a license expert either, just something I observed on other projects.

Thanks for merging these changes already and getting rid of the warnings, much appreciated :)
