### ISSUE TITLE
Can't install gem

### ISSUE THREAD

**Issue by qortex** [amazing-print/amazing_print#15]
Gem is not found on Rubygems

```sh
bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'awesomer_print' in any of the gem sources listed in your Gemfile.
```

```sh
gem install awesomer_print
ERROR:  Could not find a valid gem 'awesomer_print' (>= 0) in any repository
ERROR:  Possible alternatives: awesome_print, awesomeprint, awesome-pry, awesome_engine, awesome_link
```

**Comment by dewey** [comment]
Not sure if that's what you are looking for but in the meantime you could also install it from Github but because the gem is called awesomer_print and the repository is called amazing_print (I think that's pretty confusing so not sure why that was done) it doesn't resolve it automatically.

```
gem 'awesomer_print', git: 'https://github.com/amazing-print/amazing_print', require: true
```

**Comment by HarlemSquirrel** [comment]
Sorry for the confusion but the gem is not yet published. We're in the process of renaming and have not yet had our first release.

**Comment by HarlemSquirrel** [comment]
First release is here: https://github.com/amazing-print/amazing_print/releases/tag/v1.0.0

**Comment by HarlemSquirrel** [comment]
Let me know if this is still an issue for anyone.

**Comment by qortex** [comment]
Awesome thanks. Or should I say Amazing :)
Works fine and looks like warnings when firing up `irb` are now gone.
