### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by rubyFeedback** [amazing-print/amazing_print#16]
Hey there,

Would a short screenshot on the main page be possible? I am asking just to look how it compares to awesome_print. I am still using pp most of the time but I'd like to use RGB colours on KDE konsole one day (ap had a few display issues though, which is why I stayed on pp most of the time due to more simplicity).

**Comment by HarlemSquirrel** [comment]
There isn't much that's visually different at the moment but how about a gif?

![Peek 2020-04-15 22-56](https://user-images.githubusercontent.com/6445815/79409653-77b88b80-7f6c-11ea-9ca2-108262bd0aa1.gif)

**Comment by HarlemSquirrel** [comment]
I added a better one to the README. Let me know what you think.

**Comment by HarlemSquirrel** [comment]
Closing this since I've heard no complains :)
