### ISSUE TITLE
require "ap" Leads to Conflicts 

### ISSUE THREAD

**Issue by sshaw** [amazing-print/amazing_print#21]
Hi, first thanks for taking this over. 

Amazing and Awesome Print both allow one to say `require "ap"`. In the case of existing  Awesome Print  code this mostly works. The exception being code that references `AwesomePrint`, e.g., `AwesomePrint.irb!`.

Suggestions: 

1. In `ap.rb`: `AwesomePrint = AmazingPrint` (assume they're compatible interfaces)
1. 1 + warnings about this being Amazing Print and `AwesomePrint` constant will be removed
1. Unless a goal is backward compatibility (seems like no; from README: `... and should be used in it's place to avoid conflicts`) remove `ap.rb` from future release. Though `ruby -rap -e'...'` is nice option!
1. Do nothing!

I think 2 is best. Maybe there are other routes.

**Comment by HarlemSquirrel** [comment]
@paddor what do you think?

**Comment by paddor** [comment]
Yeah, I like option 2 using `Kernel#warn`.

**Comment by HarlemSquirrel** [comment]
Ok so we can print a warning when `require 'ap'` is called and AwesomePrint is defined. We could do the same when `AmazingPrint.irb!` is called.

**Comment by paddor** [comment]
Assuming you meant `AwesomePrint.irb!`, how would you implement that? A simple `AwesomePrint = AmazingPrint` wouldn't be possible anymore. Maybe a new object forwarding all calls to `AmazingPrint` by default could do the job.

**Comment by HarlemSquirrel** [comment]
I was thinking that we could update here

https://github.com/amazing-print/amazing_print/blob/7440a61cb80e57014d7ab45f91a5fd85b5df6aaf/lib/amazing_print/custom_defaults.rb#L38-L42

Something like 

```ruby

 def irb! 
   return unless defined?(IRB) 
  
   if defined?(AwesomePrint)
     warn 'Things may get a bit weird when AmazingPrint is used along side AwesomePrint'
   end

   IRB.version.include?('DietRB') ? diet_rb : usual_rb 
 end 
```

And/or here: https://github.com/amazing-print/amazing_print/blob/7440a61cb80e57014d7ab45f91a5fd85b5df6aaf/lib/amazing_print.rb

```
if defined?(AwesomePrint)
  warn 'Things may get a bit weird when AmazingPrint is used along side AwesomePrint'
end
```

**Comment by sshaw** [comment]
I was thinking something like this (untested): 

```rb

if defined? AwesomePrint
  warn "You've loaded AmazingPrint and AwesomePrint .. some useful info here ..."
else
  AwesomePrint = Class.new do
    AmazingPrint.methods(false).each do |name|
      define_singleton_method(name) do |*argz|
        warn "More useful info here ..."
        AmazingPrint.public_send(name, *argz)
      end
    end
  end
end
```

**Comment by HarlemSquirrel** [comment]
@sshaw what's the advantage to defining AwesomePrint within AmazingPrint?

**Comment by sshaw** [comment]
This is the gist of solution 2 in my original comment. 

If code requires ap and expects `AwesomePrint` but instead it gets `AmazingPrint` things break.

A warning implies continued execution and continued execution may depend on the existence of `AwesomePrint`. So why warn when seconds later a `NameError (uninitialized constant AwesomePrint)` will be raised. So the idea is to support Awesome Print code for a time, but warn the user about the situation and eventually remove it. 

The other 2-like option is to just assign to the constant and support it without warning or until there's reason to break compatibility and alter the existing `AwesomePrint` interface.

Hope that clarifies things!

---

In this case:

```rb
def irb! 
   return unless defined?(IRB) 
  
   if defined?(AwesomePrint)
     warn 'Things may get a bit weird when AmazingPrint is used along side AwesomePrint'
   end

   IRB.version.include?('DietRB') ? diet_rb : usual_rb 
 end 
```

It assumes one has both loaded. That's possible but I think it's probable  unless two different paths are required  since `require` only loads once.

**Comment by HarlemSquirrel** [comment]
I guess I'm less concerned about situations like 

```ruby
require 'amazing_print'
AwesomePrint.irb!
```

because it would be strange for someone to add these lines together or it would be an incomplete change to update the require statement and not the next line. 

In this case, why not keep the error so the user updates the next line?

**Comment by HarlemSquirrel** [comment]
This is quite stale now so I'm going to close unless there's still interest in this.
