### ISSUE TITLE
allow using without monkey-patches

### ISSUE THREAD

**Issue by grosser** [amazing-print/amazing_print#36]
I'd love to just do `AmazingPrint.print(:foo)` and not have to monkey-patch my core objects

**Comment by jdickey** [comment]
At least make it _optional_ by, e.g., introducing an `AmazingPrint.monkey_patch` method.

**Comment by HarlemSquirrel** [comment]
Are we talking about not loading things like https://github.com/amazing-print/amazing_print/blob/1fc8b3554284f31740f3b2589263c3078d838cb9/lib/amazing_print/core_ext/string.rb#L10-L45 when we `require 'amazing_print'`?

**Comment by grosser** [comment]
yes!
... can start with the obvious thing like colors, but ideally it would include all kinds of extra methods

**Comment by HarlemSquirrel** [comment]
Ok I think I see what you're saying. I don't think most folks are using those monkey patches directly so this could shouldn't impact how this gem is used.

**Comment by n-rodriguez** [comment]
See: https://github.com/amazing-print/amazing_print/pull/91
