### ISSUE TITLE
Rails 6.2 will deprecate `marshal_dump`; Breaks awesome_active_model_error

### ISSUE THREAD

**Issue by fire-pls** [amazing-print/amazing_print#45]
As mentioned in the Rails changelog, they will deprecate `Marshal.load` as it's too expensive performance-wise:
https://github.com/rails/rails/commit/f93b04afab15475817c638a8dbe20eb9ce672b54

Effectively, this once again breaks `awesome_active_model_error` 😅 
Building rails `6.1.0.alpha` locally & latest `amazing_print` from master I've confirmed the following behavior locally:
```ruby
[1] pry(main)> Item.first.errors
  Item Load (1.0ms)  SELECT "items".* FROM "items" ORDER BY "items"."id" ASC LIMIT $1  [["LIMIT", 1]]
(pry) output error: #<NoMethodError: undefined method `marshal_dump' for #<ActiveModel::Errors:0x00007fb4da024608>
Did you mean?  marshal_load>
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/amazing_print-1fc8b3554284/lib/amazing_print/ext/active_record.rb:87:in `awesome_active_model_error'
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/amazing_print-1fc8b3554284/lib/amazing_print/formatter.rb:28:in `format'
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/amazing_print-1fc8b3554284/lib/amazing_print/inspector.rb:124:in `unnested'
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/amazing_print-1fc8b3554284/lib/amazing_print/inspector.rb:79:in `awesome'
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/amazing_print-1fc8b3554284/lib/amazing_print/core_ext/kernel.rb:11:in `ai'
# ...pry stack, etc.
```

**Comment by HarlemSquirrel** [comment]
Thanks for reporting this. Once we get an alpha build we can begin testing against that.

**Comment by vipulnsward** [comment]
This now seems to be breaking on the released version.

**Comment by HarlemSquirrel** [comment]
@vipulnsward is this working for you when using the master branch?

**Comment by philliplongman** [comment]
I just ran into this. The master branch solved the problem for me.

**Comment by HarlemSquirrel** [comment]
Should be fixed now in https://github.com/amazing-print/amazing_print/releases/tag/v1.3.0
