### ISSUE TITLE
ActionView ap displays as string instead of HTML

### ISSUE THREAD

**Issue by jaredlt** [amazing-print/amazing_print#50]
I encountered this issue with awesome_print: https://github.com/awesome-print/awesome_print/issues/199

And discovered your fork, which I've just tried but it appears to have the same issue.

![html-print](https://user-images.githubusercontent.com/8590311/90243445-d1e83100-de26-11ea-9c25-7d6f0f5c6567.jpg)

Am I doing something wrong or is this an ongoing issue?

- Rails 5.2.1
- amazing_print 1.2.1

**Comment by daniel-rikowski** [comment]
I created a pull request for this long standing bug: #53

As a quick workaround you can use:

```
<%= raw ap @itunes %>
```

**Comment by agrberg** [comment]
My 2¢: I'm not sure if this is a bug or misleading documentation.

`tl;dr` It may be intended that the `ap` view helper is to always be passed to the `raw` method. On the other hand, as `ap` is a view helper perhaps it should be unescaped by default. AmazingPrint is already escaping the content so it should be generally safe. E.g.:
```ruby
{string_with_html: "<strong>Hi there</strong>"}.ai(html: true)
 #=> "<pre>{\n    :string_with_html<kbd style=\"color:slategray\"> =&gt; </kbd><kbd style=\"color:brown\">&quot;&lt;strong&gt;Hi there&lt;/strong&gt;&quot;</kbd>\n}</pre>"
```

I'm not sure if any of y'all remember the days of the `h` helper in Rails to explicitly sanitize output. I believe it was between Rails 2 and 3 that the default behavior changed to escape all output in a Rails template. This made explicitly unescaping HTML stored in variables or produced from methods the convention, with the notable exception of ActionView helpers such as `link_to`.

The README's section on [`ActionView`](https://github.com/amazing-print/amazing_print#actionview-convenience-method) makes the ERB case look like a bug while also explicitly indicating to use HAML's [unescape HTML syntax](https://haml.info/docs/yardoc/file.REFERENCE.html#unescaping_html) of `!= ap(…)`.

The workaround proposed by @daniel-rikowski _might_ be the intended way to use the `ap` view helper. [`raw`](https://api.rubyonrails.org/classes/ActionView/Helpers/OutputSafetyHelper.html#method-i-raw) is a Rails view helper that calls `to_s` followed by `html_safe` on the argument.

I don't know exactly how HAML's `!= ap(…)` directive works though I see many calls in the source to `html_safe`. In addition, while there probably is a difference I'm not aware of, `= raw something_to_be_unescaped` doesn't seem to produce visual differences in HAML over the idiomatic `!= something_to_be_unescaped`.

**Comment by paddor** [comment]
Can this be verified in a test case?

**Comment by HarlemSquirrel** [comment]
Since AmazingPrint is a development tool, escaping HTML by default sounds reasonable to me. I have not used this feature myself so I don't have a strong opinion. I'm trying to consider why we wouldn't want to do this.
