### ISSUE TITLE
Argument error with Ruby 2.7.2

### ISSUE THREAD

**Issue by ehutzelman** [amazing-print/amazing_print#60]
Looks like something has changed with Ruby 2.7.2 and interaction with amazing_print. In IRB, when creating a new object and setting it to a variable, we get an ArgumentError. It looks like Ruby 2.7.2/IRB is now returning the output of the object when setting to a variable, which it didn't do in 2.7.1.

Ruby 2.7.2 with amazing_print:
```
irb(main):004:0> s = String.new
Traceback (most recent call last):
ArgumentError (wrong number of arguments (given 1, expected 0))
irb(main):005:0> String.new
""
```

Ruby 2.7.2 without amazing_print:
```
irb(main):001:0> s = String.new
=> ""
irb(main):002:0> String.new
=> ""
```

Ruby 2.7.1 with amazing_print:
```
irb(main):004:0> s = String.new
irb(main):005:0> String.new
""
```

**Comment by ehutzelman** [comment]
Looks like they flipped the default for IRB ECHO_ON_ASSIGNMENT back to true. I can confirm when setting this in .irbrc, there is no issue and amazing_print works as before:

```
IRB.conf[:ECHO_ON_ASSIGNMENT] = false
```

**Comment by qortex** [comment]
Seeing that also.
Would like the echo on assignment, would look nice.

**Comment by qortex** [comment]
Ah I understand https://github.com/amazing-print/amazing_print/pull/57 fixes the issue.
Just need a release then, am I right?

**Comment by ehutzelman** [comment]
Yes, looks like this will be covered by #57, I'm closing this one out.
