### ISSUE TITLE
Peculiar error hit when doing inspect in rails

### ISSUE THREAD

**Issue by kikonen** [amazing-print/amazing_print#64]
Tried to dump out one data structure, which internally contains also references ActionView::Template, and got this

```
#<ActionView::Template::Error: uninitialized constant Concurrent::Map::DEFAULT_OBJ_ID_STR_WIDTH>
/config/initializers/did_you_mean_patch.rb:10:in `inspect'
/gems/ruby-2.7.2@drt_ui/gems/amazing_print-1.2.2/lib/amazing_print/formatter.rb:52:in `inspect'
/gems/ruby-2.7.2@drt_ui/gems/amazing_print-1.2.2/lib/amazing_print/formatter.rb:52:in `inspect'
    ... skipped 11 ...
/gems/ruby-2.7.2@drt_ui/gems/amazing_print-1.2.2/lib/amazing_print/core_ext/kernel.rb:21:in `ap'```
```

**Comment by HarlemSquirrel** [comment]
Hi @kikonen if you can share how to reproduce this that would be really helpful. What version of Rails are you using here?

It looks like it may be happening when `#inspect` is called.
https://github.com/amazing-print/amazing_print/blob/19db166075a10feab1e21c5935c0582a27ac95b5/lib/amazing_print/formatter.rb#L52

**Comment by HarlemSquirrel** [comment]
Let us know if this is still a problem.
