### ISSUE TITLE
Default colors only last for one print

### ISSUE THREAD

**Issue by benlieb** [amazing-print/amazing_print#73]
This is a bit strange, but I'm noticing that the default colors I have configured work on the first print, but then they revert  back to the default colors. I have a black background and the default blue for numbers is hard to see, so I've changed it to cyan:

![image](https://user-images.githubusercontent.com/634562/116349017-f6611f00-a7a3-11eb-8a1c-e9f5eba43da2.png)

Here I am loading the same object twice, and the first time the numbers are cyan, but the second time they are blue:

![image](https://user-images.githubusercontent.com/634562/116348996-eb0df380-a7a3-11eb-987c-5d3c8df3c568.png)

Stranger still is that when I print out the defaults, the first time the colors are "right" but the defaults are not the ones I set, and the second time the color goes back to blue:

![image](https://user-images.githubusercontent.com/634562/116349217-6374b480-a7a4-11eb-991e-17ad55722066.png)

**Comment by benlieb** [comment]
On further inspection I think this might be because I put the AmazingPrint.defaults in a rails initializer, not `~/.aprc`. Putting it in `~/.aprc` works, but I'd prefer to version this with my app. Is that not possible?

**Comment by HarlemSquirrel** [comment]
Today, each new instance of `AmazingPrint::Inspector` loads settings from `.aprc` so I think what's happening is that the first time your Rails initilizer is running the first inspector loads and sets the new defaults but then invoking ap again reloads the settings.

This is definitely not efficient but allows or "hot reloading" settings that could change while pry session is open. This would be a major change but I think we should consider _not_ reloading these settings so often and instead provide some command like `AmazingPrint.reload!`

@paddor what do you think?

**Comment by benlieb** [comment]
@HarlemSquirrel well for my specific needs I can see more use from an approach where AmazingPrint checks first for app-level settings (eg, in an initializer) and just uses those settings in memory without reloading. This would allow me to have application-specific settings, and also version those settings in my git project. 

I can't think of a time where hot loading would be anything I could benefit from personally, though I wouldn't be surprised if there's a good use-case for that for others.

**Comment by HarlemSquirrel** [comment]
@benlieb Could you try out the branch from the above PR and let me know if that fixes this issue?

**Comment by paddor** [comment]
> Today, each new instance of `AmazingPrint::Inspector` loads settings from `.aprc` so I think what's happening is that the first time your Rails initilizer is running the first inspector loads and sets the new defaults but then invoking ap again reloads the settings.
> 
> This is definitely not efficient but allows or "hot reloading" settings that could change while pry session is open. This would be a major change but I think we should consider _not_ reloading these settings so often and instead provide some command like `AmazingPrint.reload!`
> 
> @paddor what do you think?

I definitely think that `.aprc` should be loaded only once. I believe, years ago, I even used to have monkey patch in place that prevented this because it was too much IO. `AmazingPrint.reload!` would be perfect. PR welcome.

**Comment by benlieb** [comment]
@HarlemSquirrel I am absolutely swamped with work right now, so I probably won't be testing this out any time soon. Happy to hear of updates if they come though..
